language: node_js

node_js:
  - 'stable'

cache:
  npm: false

services:
  - postgresql
  - redis-server

before_script:
  - npm install codeclimate-test-reporter nyc -g
  - psql -c 'create database quinca-paradi_test;' -U postgres

script:
  - npm test

after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
